require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120
